"""empty message

Revision ID: cc995067710b
Revises: 5ad3243edc3e
Create Date: 2019-09-09 14:18:15.896608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc995067710b'
down_revision = '5ad3243edc3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('entity_type', sa.String(length=10), nullable=True))
    op.add_column('businesses_version', sa.Column('entity_type', sa.String(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses_version', 'entity_type')
    op.drop_column('businesses', 'entity_type')
    # ### end Alembic commands ###
